### ISSUE TITLE
Run the command service API example

### ISSUE THREAD

**Issue by zonca** [tmtsoftware/pycsw#3]
I am trying to run the example of using the Command service API from https://tmtsoftware.github.io/pycsw/index.html#command-service-api

I have:

* latest csw-services running on host setup by Chris
* pycsw 3.0.6 with all requirements

If I try to execute it, it just runs through until the end without stopping at `commandServer.start()` and without printing anything.

what else do I need?  then how do I send it a command?
thanks

**Comment by zonca** [comment]
or maybe you have a prototype for an Assembly ready to go?

**Comment by abrighton** [comment]
The example in TestCommandServer.py shows how you can implement part of an assembly or HCD in python.
When I run it in Intellij Idea, I get this output:

```
Registering with location service using port 8082
Starting test command server on port 8082
======== Running on http://0.0.0.0:8082 ========
(Press CTRL+C to quit)
```

Then it waits until the process is killed.

There is also some similar code under `tests` and a test assembly under `tests/testSupport` that forwards commands to the python code and waits for the replies. See tests/test_commands_with_assembly.py.

**Comment by abrighton** [comment]
Or from the command line:
```
> pip3 install tmtpycsw
> python3 TestCommandServer.py
Registering with location service using port 8082
Starting test command server on port 8082
======== Running on http://0.0.0.0:8082 ========
(Press CTRL+C to quit)

```

**Comment by zonca** [comment]
Thanks,
I will try it out,

I am looking through `tests/test_commands_with_assembly.py`, I don't see where it is sending any command, can you point me to the right call?

I just need a snippet I can call to check I can communicate with the `CommandServer`

**Comment by abrighton** [comment]
The python support for CSW is currently only for receiving commands, not sending them.
In the test, the commands are sent to the python code from the Scala based assembly.
