### ISSUE TITLE
Using the Scala testSupport assembly

### ISSUE THREAD

**Issue by zonca** [tmtsoftware/pycsw#4]
In order to test the Python based assembly, I need to run the Scala assembly as mentioned in https://github.com/tmtsoftware/pycsw/issues/3#issuecomment-802650740

I am following instructions at https://github.com/tmtsoftware/pycsw/tree/master/tests,
is this the right place? It refers to `csw-services.sh`, is it possible it refers to a old CSW release? (now it is `csw-services` and doesn't support stop)

Anyway, I managed to run `sbt stage` fine, then when I run:

    test-deploy/target/universal/stage/bin/test-container-cmd-app --local test-deploy/src/main/resources/TestContainer.conf

I get the error `INTERFACE_NAME env variable is not set`

I tried setting `INTERFACE_NAME=eth0` and it seems to start.

Now is this continually sending a command? what kind of command? can I receive it from `TestCommandServer.py`?

**Comment by abrighton** [comment]
The references to csw-services.sh in the comments and README were out of date. I checked in the changes. 
csw-3.0.1 now uses csw-services as installed by coursier (see https://tmtsoftware.github.io/csw/3.0.1/apps/cswservices.html).

The test assembly only calls sendCommandsToPython() once after it locates the python based command service. 
See https://github.com/tmtsoftware/pycsw/blob/master/tests/testSupport/test-assembly/src/main/scala/org/tmt/csw/testassembly/TestAssemblyHandlers.scala.

The test assembly is only used here to validate that the python code is working.
You should be able to talk to a python based CSW command service in the same way as any other CSW HCD or assembly,
although I think the plan was that it would be used to support other HCDs or assemblies.

If you have access to the TMT slack channel (#tmt-sw-programming), that would be a better place to ask questions.

**Comment by zonca** [comment]
unfortunately I work only 20% on this project, I cannot commit to synchronous communication. Is there a way to have asynchronous support?

**Comment by kgillies** [comment]
The way to get asynchronous support is to put a message on the #tmt-sw-programming TMT Slack channel or post an issue on the CSW maintenance JIRA: https://tmt-project.atlassian.net/wiki/spaces/DEOPSCSW/overview.  For good or bad, these are the systems set up by the project to support development.

**Comment by zonca** [comment]
thanks, that was what I was asking for, CSW maintenance JIRA can work. I sent you email.
